services:
  - type: web
    name: todo-api
    env: java
    region: oregon
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/todo-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "10000"
    healthCheckPath: /actuator/health

  - type: postgres
    name: todo-db
    databaseName: todo_db
    user: todo_user